// This file is automatically generated by qtc from "base.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// 这是我们模板的基础实现

//line base.qtpl:2
package templates

//line base.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line base.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line base.qtpl:3
type Partial interface {
	//line base.qtpl:3
	Body() string
	//line base.qtpl:3
	StreamBody(qw422016 *qt422016.Writer)
	//line base.qtpl:3
	WriteBody(qq422016 qtio422016.Writer)
//line base.qtpl:3
}

// 模板编写实现Partial接口的模板

//line base.qtpl:8
func StreamTemplate(qw422016 *qt422016.Writer, p Partial) {
	//line base.qtpl:8
	qw422016.N().S(`
<html>
	<head>
		<title>Quicktemplate integration with Iris</title>
	</head>
	<body>
		<div>
			Header contents here...
		</div>
		<div style="margin:10px;">
			`)
	//line base.qtpl:18
	p.StreamBody(qw422016)
	//line base.qtpl:18
	qw422016.N().S(`
		</div>
	</body>
	<footer>
		Footer contents here...
	</footer>
</html>
`)
//line base.qtpl:25
}

//line base.qtpl:25
func WriteTemplate(qq422016 qtio422016.Writer, p Partial) {
	//line base.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line base.qtpl:25
	StreamTemplate(qw422016, p)
	//line base.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line base.qtpl:25
}

//line base.qtpl:25
func Template(p Partial) string {
	//line base.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line base.qtpl:25
	WriteTemplate(qb422016, p)
	//line base.qtpl:25
	qs422016 := string(qb422016.B)
	//line base.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line base.qtpl:25
	return qs422016
//line base.qtpl:25
}

// 基本模板实现。 如果需要，其他页面可以继承
// 仅覆盖某些部分方法。

//line base.qtpl:28
type Base struct{}

//line base.qtpl:29
func (b *Base) StreamBody(qw422016 *qt422016.Writer) {
//line base.qtpl:29
qw422016.N().S(`This is the base body`) }

//line base.qtpl:29
//line base.qtpl:29
func (b *Base) WriteBody(qq422016 qtio422016.Writer) {
	//line base.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line base.qtpl:29
	b.StreamBody(qw422016)
	//line base.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line base.qtpl:29
}

//line base.qtpl:29
func (b *Base) Body() string {
	//line base.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
	//line base.qtpl:29
	b.WriteBody(qb422016)
	//line base.qtpl:29
	qs422016 := string(qb422016.B)
	//line base.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
	//line base.qtpl:29
	return qs422016
//line base.qtpl:29
}
